# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 074f3b82a0e520d8e0a552ef8fb0eace1dc76f1a09eef30a39d365600ce41582c4a769bfb9a4af72cecfde8bbd121b63d3f5449a67c791f9528a88e9997dc39e

test:
  secret_key_base: c9c57b1a08bd4ebc93780b3b1ceedf13d51ebdcd2117ca791156e7011613bc7bec168566657dcef376d61b26aeca0f740954de6c4f1f627440df6bf0f96432b6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
